// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimeMonitoringService.proto

package smart.medical.realTimeMonitoringService;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 time = 1;</code>
   */
  int getTime();
}
