// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimeMonitoringService.proto

package smart.medical.realTimeMonitoringService;

public interface LowBloodOxygenAlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.LowBloodOxygenAlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float num = 1;</code>
   */
  float getNum();
}
