// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimeMonitoringService.proto

package smart.medical.realTimeMonitoringService;

public final class realTimeMonitoringServiceImpl {
  private realTimeMonitoringServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_HeartbeatReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_HeartbeatReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_OneClickCancellationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_OneClickCancellationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_CancellationStatusReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_CancellationStatusReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037RealTimeMonitoringService.proto\022\005smart" +
      "\" \n\020HeartbeatRequest\022\014\n\004time\030\001 \001(\005\" \n\016He" +
      "artbeatReply\022\016\n\006result\030\001 \001(\005\"3\n\033OneClick" +
      "CancellationRequest\022\024\n\014cancellation\030\001 \001(" +
      "\t\"*\n\027CancellationStatusReply\022\017\n\007message\030" +
      "\001 \001(\t2m\n\031RealTimeMonitoringService\022P\n\032re" +
      "alTimeHeartbeatDetection\022\027.smart.Heartbe" +
      "atRequest\032\025.smart.HeartbeatReply\"\0000\001BJ\n\'" +
      "smart.medical.realTimeMonitoringServiceB" +
      "\035realTimeMonitoringServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_smart_HeartbeatReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_HeartbeatReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_HeartbeatReply_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_smart_OneClickCancellationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smart_OneClickCancellationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_OneClickCancellationRequest_descriptor,
        new java.lang.String[] { "Cancellation", });
    internal_static_smart_CancellationStatusReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smart_CancellationStatusReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_CancellationStatusReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
