// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAppointmentService.proto

package smart.medical.appointmentService;

public final class appointmentServiceImpl {
  private appointmentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_AppointmentInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_AppointmentInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_AppointmentInfoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_AppointmentInfoReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035SmartAppointmentService.proto\022\005smart\"D" +
      "\n\026AppointmentInfoRequest\022\014\n\004date\030\001 \001(\t\022\016" +
      "\n\006doctor\030\002 \001(\t\022\014\n\004time\030\003 \001(\t\"N\n\024Appointm" +
      "entInfoReply\022\020\n\010msg_date\030\001 \001(\t\022\022\n\nmsg_do" +
      "ctor\030\002 \001(\t\022\020\n\010msg_time\030\003 \001(\t2p\n\027SmartApp" +
      "ointmentService\022U\n\021mobileAppointment\022\035.s" +
      "mart.AppointmentInfoRequest\032\033.smart.Appo" +
      "intmentInfoReply\"\000(\0010\001B<\n smart.medical." +
      "appointmentServiceB\026appointmentServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_AppointmentInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_AppointmentInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_AppointmentInfoRequest_descriptor,
        new java.lang.String[] { "Date", "Doctor", "Time", });
    internal_static_smart_AppointmentInfoReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_AppointmentInfoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_AppointmentInfoReply_descriptor,
        new java.lang.String[] { "MsgDate", "MsgDoctor", "MsgTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
