// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAppointmentService.proto

package smart.medical.appointmentService;

/**
 * Protobuf type {@code smart.AppointmentInfoReply}
 */
public  final class AppointmentInfoReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smart.AppointmentInfoReply)
    AppointmentInfoReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppointmentInfoReply.newBuilder() to construct.
  private AppointmentInfoReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppointmentInfoReply() {
    msgDate_ = "";
    msgDoctor_ = "";
    msgTime_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppointmentInfoReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            msgDate_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            msgDoctor_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            msgTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smart.medical.appointmentService.appointmentServiceImpl.internal_static_smart_AppointmentInfoReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smart.medical.appointmentService.appointmentServiceImpl.internal_static_smart_AppointmentInfoReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smart.medical.appointmentService.AppointmentInfoReply.class, smart.medical.appointmentService.AppointmentInfoReply.Builder.class);
  }

  public static final int MSG_DATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object msgDate_;
  /**
   * <code>string msg_date = 1;</code>
   */
  public java.lang.String getMsgDate() {
    java.lang.Object ref = msgDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgDate_ = s;
      return s;
    }
  }
  /**
   * <code>string msg_date = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMsgDateBytes() {
    java.lang.Object ref = msgDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_DOCTOR_FIELD_NUMBER = 2;
  private volatile java.lang.Object msgDoctor_;
  /**
   * <code>string msg_doctor = 2;</code>
   */
  public java.lang.String getMsgDoctor() {
    java.lang.Object ref = msgDoctor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgDoctor_ = s;
      return s;
    }
  }
  /**
   * <code>string msg_doctor = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMsgDoctorBytes() {
    java.lang.Object ref = msgDoctor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgDoctor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_TIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object msgTime_;
  /**
   * <code>string msg_time = 3;</code>
   */
  public java.lang.String getMsgTime() {
    java.lang.Object ref = msgTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgTime_ = s;
      return s;
    }
  }
  /**
   * <code>string msg_time = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMsgTimeBytes() {
    java.lang.Object ref = msgTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMsgDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgDate_);
    }
    if (!getMsgDoctorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgDoctor_);
    }
    if (!getMsgTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msgTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMsgDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgDate_);
    }
    if (!getMsgDoctorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgDoctor_);
    }
    if (!getMsgTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msgTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smart.medical.appointmentService.AppointmentInfoReply)) {
      return super.equals(obj);
    }
    smart.medical.appointmentService.AppointmentInfoReply other = (smart.medical.appointmentService.AppointmentInfoReply) obj;

    boolean result = true;
    result = result && getMsgDate()
        .equals(other.getMsgDate());
    result = result && getMsgDoctor()
        .equals(other.getMsgDoctor());
    result = result && getMsgTime()
        .equals(other.getMsgTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSG_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgDate().hashCode();
    hash = (37 * hash) + MSG_DOCTOR_FIELD_NUMBER;
    hash = (53 * hash) + getMsgDoctor().hashCode();
    hash = (37 * hash) + MSG_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getMsgTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smart.medical.appointmentService.AppointmentInfoReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smart.medical.appointmentService.AppointmentInfoReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smart.AppointmentInfoReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smart.AppointmentInfoReply)
      smart.medical.appointmentService.AppointmentInfoReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smart.medical.appointmentService.appointmentServiceImpl.internal_static_smart_AppointmentInfoReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smart.medical.appointmentService.appointmentServiceImpl.internal_static_smart_AppointmentInfoReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smart.medical.appointmentService.AppointmentInfoReply.class, smart.medical.appointmentService.AppointmentInfoReply.Builder.class);
    }

    // Construct using smart.medical.appointmentService.AppointmentInfoReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgDate_ = "";

      msgDoctor_ = "";

      msgTime_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smart.medical.appointmentService.appointmentServiceImpl.internal_static_smart_AppointmentInfoReply_descriptor;
    }

    @java.lang.Override
    public smart.medical.appointmentService.AppointmentInfoReply getDefaultInstanceForType() {
      return smart.medical.appointmentService.AppointmentInfoReply.getDefaultInstance();
    }

    @java.lang.Override
    public smart.medical.appointmentService.AppointmentInfoReply build() {
      smart.medical.appointmentService.AppointmentInfoReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smart.medical.appointmentService.AppointmentInfoReply buildPartial() {
      smart.medical.appointmentService.AppointmentInfoReply result = new smart.medical.appointmentService.AppointmentInfoReply(this);
      result.msgDate_ = msgDate_;
      result.msgDoctor_ = msgDoctor_;
      result.msgTime_ = msgTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smart.medical.appointmentService.AppointmentInfoReply) {
        return mergeFrom((smart.medical.appointmentService.AppointmentInfoReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smart.medical.appointmentService.AppointmentInfoReply other) {
      if (other == smart.medical.appointmentService.AppointmentInfoReply.getDefaultInstance()) return this;
      if (!other.getMsgDate().isEmpty()) {
        msgDate_ = other.msgDate_;
        onChanged();
      }
      if (!other.getMsgDoctor().isEmpty()) {
        msgDoctor_ = other.msgDoctor_;
        onChanged();
      }
      if (!other.getMsgTime().isEmpty()) {
        msgTime_ = other.msgTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smart.medical.appointmentService.AppointmentInfoReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smart.medical.appointmentService.AppointmentInfoReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object msgDate_ = "";
    /**
     * <code>string msg_date = 1;</code>
     */
    public java.lang.String getMsgDate() {
      java.lang.Object ref = msgDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg_date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgDateBytes() {
      java.lang.Object ref = msgDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg_date = 1;</code>
     */
    public Builder setMsgDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg_date = 1;</code>
     */
    public Builder clearMsgDate() {
      
      msgDate_ = getDefaultInstance().getMsgDate();
      onChanged();
      return this;
    }
    /**
     * <code>string msg_date = 1;</code>
     */
    public Builder setMsgDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgDoctor_ = "";
    /**
     * <code>string msg_doctor = 2;</code>
     */
    public java.lang.String getMsgDoctor() {
      java.lang.Object ref = msgDoctor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgDoctor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg_doctor = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgDoctorBytes() {
      java.lang.Object ref = msgDoctor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgDoctor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg_doctor = 2;</code>
     */
    public Builder setMsgDoctor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgDoctor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg_doctor = 2;</code>
     */
    public Builder clearMsgDoctor() {
      
      msgDoctor_ = getDefaultInstance().getMsgDoctor();
      onChanged();
      return this;
    }
    /**
     * <code>string msg_doctor = 2;</code>
     */
    public Builder setMsgDoctorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgDoctor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgTime_ = "";
    /**
     * <code>string msg_time = 3;</code>
     */
    public java.lang.String getMsgTime() {
      java.lang.Object ref = msgTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTimeBytes() {
      java.lang.Object ref = msgTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg_time = 3;</code>
     */
    public Builder setMsgTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg_time = 3;</code>
     */
    public Builder clearMsgTime() {
      
      msgTime_ = getDefaultInstance().getMsgTime();
      onChanged();
      return this;
    }
    /**
     * <code>string msg_time = 3;</code>
     */
    public Builder setMsgTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgTime_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smart.AppointmentInfoReply)
  }

  // @@protoc_insertion_point(class_scope:smart.AppointmentInfoReply)
  private static final smart.medical.appointmentService.AppointmentInfoReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smart.medical.appointmentService.AppointmentInfoReply();
  }

  public static smart.medical.appointmentService.AppointmentInfoReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppointmentInfoReply>
      PARSER = new com.google.protobuf.AbstractParser<AppointmentInfoReply>() {
    @java.lang.Override
    public AppointmentInfoReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppointmentInfoReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppointmentInfoReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppointmentInfoReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smart.medical.appointmentService.AppointmentInfoReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

