// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAppointmentService.proto

package smart.medical.appointmentService;

public interface AppointmentInfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.AppointmentInfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg_date = 1;</code>
   */
  java.lang.String getMsgDate();
  /**
   * <code>string msg_date = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgDateBytes();

  /**
   * <code>string msg_doctor = 2;</code>
   */
  java.lang.String getMsgDoctor();
  /**
   * <code>string msg_doctor = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgDoctorBytes();

  /**
   * <code>string msg_time = 3;</code>
   */
  java.lang.String getMsgTime();
  /**
   * <code>string msg_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgTimeBytes();
}
