// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAppointmentService.proto

package smart.medical.appointmentService;

public interface AppointmentInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.AppointmentInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Info = 1;</code>
   */
  java.lang.String getInfo();
  /**
   * <code>string Info = 1;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();
}
