// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAppointmentService.proto

package smart.medical.appointmentService;

public interface AppointmentInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.AppointmentInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string doctor = 2;</code>
   */
  java.lang.String getDoctor();
  /**
   * <code>string doctor = 2;</code>
   */
  com.google.protobuf.ByteString
      getDoctorBytes();

  /**
   * <code>string time = 3;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
