// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAppointmentService.proto

package smart.medical.appointmentService;

public interface OneClickCancellationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.OneClickCancellationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cancellation = 1;</code>
   */
  java.lang.String getCancellation();
  /**
   * <code>string cancellation = 1;</code>
   */
  com.google.protobuf.ByteString
      getCancellationBytes();
}
