// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntelligentArchivingService.proto

package smart.medical.intelligentArchivingService;

public interface DoctorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.DoctorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestPatientsDoctor = 1;</code>
   */
  java.lang.String getRequestPatientsDoctor();
  /**
   * <code>string requestPatientsDoctor = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestPatientsDoctorBytes();
}
