// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntelligentArchivingService.proto

package smart.medical.intelligentArchivingService;

public interface DoctorReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.DoctorReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctor = 1;</code>
   */
  java.lang.String getDoctor();
  /**
   * <code>string doctor = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoctorBytes();
}
