// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntelligentArchivingService.proto

package smart.medical.intelligentArchivingService;

public interface HealthInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.HealthInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string gender = 2;</code>
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 2;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string diagnose = 3;</code>
   */
  java.lang.String getDiagnose();
  /**
   * <code>string diagnose = 3;</code>
   */
  com.google.protobuf.ByteString
      getDiagnoseBytes();
}
