// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntelligentArchivingService.proto

package smart.medical.intelligentArchivingService;

public interface ProfileNoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart.ProfileNoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
